---
- hosts: flask_nodes
  become: yes
  vars: 
    APP_REPO: "https://github.com/jan-podolanko/CeneoScrapper"
    APP_NAME: "Ceneo"
  tasks:
    - name: "python" 
      yum:
        name: python3-pip, git
        state: present
    - name: "repo"
      git:
        repo: "{{ APP_REPO }}"
        dest: "/opt/{{ APP_NAME }}"
    - name: "user"
      user: 
        name: "{{ APP_NAME }}"
    - name: "permissions"
      file:
        owner: "{{APP_NAME}}"
        group: "{{APP_NAME}}"
        path: "/opt/{{APP_NAME}}"
        recurse: yes
    - name: "venv, reqs"
      pip:
        requirements: "/opt/{{ APP_NAME }}/requirements.txt"
        virtualenv: "/opt/{{ APP_NAME }}/.venv"
        virtualenv_command: python3 -m venv
    - name: "register"
      template:
        src: files/app.service
        dest: "/etc/systemd/system/{{ APP_NAME }}.service"
    - name: "start"
      systemd:
        daemon_reload: yes
        name: "{{ APP_NAME }}"
        state: restarted

- hosts: load_balancer
  become: yes
  vars:
    app_ips:
      - 172.31.4.75:80
  tasks:
    - name: install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: install nginx
      yum:
        name: nginx
        state: present
    - name: put nginx conf
      template:
        src: files/proxy.conf
        dest: /etc/nginx/conf.d/blog.conf
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded